name: Laravel >= 10 & PHP >= 8.2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Laravel ${{ matrix.laravel }}
    strategy:
      fail-fast: true
      matrix:
        laravel: [10.*, 11.*]
        php: [8.2, 8.3]
        dependency-version: [prefer-lowest, prefer-stable]
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        run: |
            composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
            composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
      - name: Run tests
        run: vendor/bin/phpunit --testsuite=Feature --colors=always